const poemData = [
    { text: "昔", py: "xī", zh: "从前，以前。", en: "In the past / once upon a time.", exam: true },
    { text: "有", py: "yǒu", zh: "有一个。", en: "there was a" },
    { text: "愚人", py: "yú rén", zh: "愚笨的人，傻子。", en: "foolish man," },
    { text: "，", punc: true },
    { text: "至于", py: "zhì yú", zh: "动词短语，到了，来到。“至”，到；“于”，到。", en: "who went to", exam: true },
    { text: "他家", py: "tā jiā", zh: "别人的家里。", en: "another person's house." },
    { text: "。", punc: true },
    { text: "主人", py: "zhǔ rén", zh: "主人家。", en: "The host" },
    { text: "与", py: "yǔ", zh: "动词，给予，给。“与食”，给东西吃。", en: "gave him", exam: true },
    { text: "食", py: "shí", zh: "食物，东西吃。", en: "food to eat," },
    { text: "，", punc: true },
    { text: "嫌", py: "xián", zh: "嫌弃，抱怨。", en: "but the foolish man complained that" },
    { text: "淡", py: "dàn", zh: "清淡，没有味道。", en: "it was too bland" },
    { text: "无味", py: "wú wèi", zh: "没有滋味。", en: "and tasteless." },
    { text: "。", punc: true },
    { text: "主人", py: "zhǔ rén", zh: "主人。", en: "The host" },
    { text: "闻已", py: "wén yǐ", zh: "听了之后。“已”，完毕、之后。", en: "heard this", exam: true },
    { text: "，", punc: true },
    { text: "更为", py: "gèng wèi", zh: "替他重新，更加。“更”，重新；“为”，替。", en: "and especially for him," },
    { text: "益", py: "yì", zh: "动词，增加，添加。", en: "added more", exam: true },
    { text: "盐", py: "yán", zh: "食盐。", en: "salt." },
    { text: "。", punc: true },
    { text: "既", py: "jì", zh: "连词，等到……之后，已经。", en: "After", exam: true },
    { text: "得", py: "dé", zh: "得到，尝到。", en: "getting" },
    { text: "盐", py: "yán", zh: "盐。", en: "the salt," },
    { text: "美", py: "měi", zh: "形容词作动词，美味，觉得味道鲜美。", en: "the food tasted delicious,", exam: true },
    { text: "，", punc: true },
    { text: "便", py: "biàn", zh: "于是，就。", en: "so he" },
    { text: "自念言", py: "zì niàn yán", zh: "心里自言自语，暗自琢磨。“念”，思考、想。", en: "thought to himself:", exam: true },
    { text: "：“", punc: true },
    { text: "所以", py: "suǒ yǐ", zh: "……的原因（特殊代词短语）。", en: "The reason why", exam: true },
    { text: "美者", py: "měi zhě", zh: "味道鲜美（的原因）。", en: "it tastes delicious" },
    { text: "，", punc: true },
    { text: "缘", py: "yuán", zh: "介词，因为，由于。", en: "is because", exam: true },
    { text: "有", py: "yǒu", zh: "有。", en: "there is" },
    { text: "盐", py: "yán", zh: "盐。", en: "salt" },
    { text: "故", py: "gù", zh: "名词，缘故、原因（与前面的“缘”呼应，表因果）。", en: "involved.", exam: true },
    { text: "。", punc: true },
    { text: "少", py: "shǎo", zh: "少量的（盐）。", en: "A small amount of it" },
    { text: "有", py: "yǒu", zh: "有，加入。", en: "is already" },
    { text: "尚尔", py: "shàng ěr", zh: "尚且如此。“尚”，尚且；“尔”，如此、这样。", en: "like this,", exam: true },
    { text: "，", punc: true },
    { text: "况复", py: "kuàng fù", zh: "何况，更何况。“况”，况且；“复”，又、再。", en: "let alone", exam: true },
    { text: "多", py: "duō", zh: "大量的（盐）。", en: "a large amount" },
    { text: "也", py: "yě", zh: "语气助词，表感叹或反问。", en: "of it?”" },
    { text: "？”", punc: true },
    { text: "愚人", py: "yú rén", zh: "愚笨的人。", en: "The foolish man" },
    { text: "无智", py: "wú zhì", zh: "没有智慧，没有头脑。", en: "lacked intelligence," },
    { text: "，", punc: true },
    { text: "便", py: "biàn", zh: "就，于是。", en: "and so he" },
    { text: "空食盐", py: "kōng shí yán", zh: "空口吃盐，只吃盐不配饭菜。“空”，空口、单独。", en: "ate the salt by itself.", exam: true },
    { text: "。", punc: true },
    { text: "食已", py: "shí yǐ", zh: "吃完之后。“已”，完毕、完。", en: "After eating it," },
    { text: "口爽", py: "kǒu shuǎng", zh: "口味败坏，味觉麻木麻痹（古汉语中“爽”常指败坏、差错）。", en: "his taste buds were ruined", exam: true },
    { text: "，", punc: true },
    { text: "反", py: "fǎn", zh: "反而。", en: "and it turned into" },
    { text: "为", py: "wéi", zh: "成为，变成。", en: "成为" },
    { text: "其", py: "qí", zh: "它的。", en: "它的" },
    { text: "患", py: "huàn", zh: "祸害，灾祸，痛苦。", en: "a disaster for him.", exam: true },
    { text: "。", punc: true }
];
